list p=16F887

_CONFIG1    EQU	H'2007'
_CONFIG2    EQU H'2008'
STATUS	    EQU H'0003'
TRISA	    EQU H'0085'
ANSEL	    EQU H'0188'
ANSELH	    EQU H'0189'
PORTA	    EQU H'0005'
RA0	    EQU H'0000'
RP0	    EQU H'0005'
RP1	    EQU H'0006'
OSCCON	    EQU H'008F'
	    
;CONFIGURACION DE BITS
__CONFIG _CONFIG1, 0XE3F4
__CONFIG _CONFIG2, 0XFEFF

;DEFINICION DE VARIABLES
CBLOCK 0X20
    CONT1
    CONT2
ENDC
	    
ORG .0
  BSF	    STATUS, RP0
  BCF	    STATUS, RP1 ;SELECCIONO EL BANCO 1
  BCF	    TRISA,0	;RA0 SALIDA
  MOVLW	    0X11	;EL OSCILADOR INTERNO ENABLE, Y Fosc = 125KHz
  MOVWF	    OSCCON	;
  BANKSEL   ANSEL	;SELECCIONO EL BANCO 3
  CLRF	    ANSEL	;SE CLAREA EL REGISTRO ANSEL
  BANKSEL   PORTA   
  
LOOP:
    BTFSS   PORTA,RA0
    GOTO    $+3
    BCF	    PORTA,RA0
    GOTO    $+2
    BSF	    PORTA, RA0	;PONEMOS EN 1 EL BIT RA0 DEL PORTA
    CALL    RETARDO
    GOTO    LOOP	;RETORNAMOS A LA ETIQUETA LOOP
    
    #INCLUDE "RETARDO.INC"
    
END
	    
	    


